### ISSUE TITLE
External mapper injection

### ISSUE THREAD

**Issue by sonytricoire** [JoanZapata/simple-mapper#10]
I need to inject an existing mapper into another mapper to avoid duplication mapping rules.

For example, if want to inject an existing mapper to manage the ConfigProfile class mapping, I expect something like

```
mapper1 = new Mapper()
                .biMapping(ConfigProfile.class, ConfigProfileDTO.class);
...
mapper = new Mapper()
                .biMapping(Device.class, DeviceDTO.class)
                .injectMapper(mapper1, ConfigProfile.class);

```

**Comment by JoanZapata** [comment]
What I would do to avoid duplication is to have only one `Mapper` instance for all the mappings, as `Mapper` is thread-safe and there shouldn't be conflicting cases.

In your `.injectMapper(mapper1, ConfigProfile.class)`, what is `ConfigProfile.class` for ? 

If that means "I want the `ConfigProfile` class to be mapped only by `mapper1`, then what about that :

``` java
Mapper mapper = new Mapper()
    .custom(new CustomMapper<ConfigProfile, ConfigProfileDTO >() {
        @Override
        public ConfigProfileDTO customMapping(ConfigProfile source) {
            return mapper1.map(source); // or anything else
        }
    };
});
```

I think it's better because it allows for other mapping libraries to be easily integrated in simple-mapper.

Would it be ok for you ?

**Comment by sonytricoire** [comment]
Yep seems right !
